# Generated by Django 4.2.5 on 2023-10-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminzone', '0002_delete_facalty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facalty',
            fields=[
                ('image', models.ImageField(default=None, max_length=250, null=True, upload_to='image/faculty_images/')),
                ('fid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=40)),
                ('about', models.CharField(max_length=400)),
                ('salary', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('qua', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=10)),
            ],
        ),
    ]
