# Generated by Django 4.2.5 on 2023-10-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nfc',
            fields=[
                ('nfcid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nfc', models.CharField(max_length=200)),
            ],
        ),
    ]
