# Generated by Django 4.2.5 on 2023-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0004_nfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('fid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
