# Generated by Django 4.2.5 on 2023-10-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminzone', '0005_attend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('fid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=40)),
                ('salary', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
