# Generated by Django 4.2.5 on 2023-10-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('stdid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stdname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=20)),
                ('feedtype', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
