# Generated by Django 4.2.5 on 2023-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('stdid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stdname', models.CharField(max_length=50)),
                ('brancht', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('fr', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
