# Generated by Django 4.2.5 on 2023-10-19 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentzone', '0002_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='brancht',
            new_name='branch',
        ),
    ]
