# Generated by Django 4.2.5 on 2023-10-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentzone', '0003_rename_brancht_leave_branch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
