# Generated by Django 4.2.5 on 2023-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('stdid', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('stdname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('about', models.CharField(max_length=400)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('qua', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=10)),
            ],
        ),
    ]
