# Generated by Django 4.2.5 on 2023-10-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facaltyzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('fid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=20)),
                ('fr', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
