# Generated by Django 4.2.5 on 2023-10-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facaltyzone', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='image/student_images/'),
        ),
    ]
