# Generated by Django 4.2.5 on 2023-10-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facaltyzone', '0003_alter_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('fid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=20)),
                ('feedtype', models.CharField(max_length=20)),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
