# Generated by Django 4.2.5 on 2023-10-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facaltyzone', '0004_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNfc',
            fields=[
                ('nfcid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nfc', models.CharField(max_length=200)),
            ],
        ),
    ]
