# Generated by Django 4.2.5 on 2023-10-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facaltyzone', '0005_snfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAttend',
            fields=[
                ('stdid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stdname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
