# Generated by Django 4.2.5 on 2023-10-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facaltyzone', '0006_sattend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SAttend',
        ),
    ]
